ENDPOINT_MENU_PERMISSION = {
    "dashboard.index": "menu_dashboard",
    "clauses.list_clauses": "menu_clauses",
    "controls.list_controls": "menu_controls",
    "soa.list_soa": "menu_soa",
    "management_review.list_reviews": "menu_reviews",
    "kpi.dashboard": "menu_kpi",
    "risks.list_risks": "menu_risks",
    "assets.list_assets": "menu_assets",
    "assignments.list_assignments": "menu_assignments",
    "incidents.list_incidents": "menu_incidents",
    "policies.list_policies": "menu_policies",
    "filled_forms.list_filled_forms": "menu_filled_forms",
    "audits.list_audits": "menu_audits",
    "business_continuity.dashboard": "menu_business_continuity",
    "capa.list_capas": "menu_capa",
    "training.list_courses": "menu_training",
    "suppliers.list_suppliers": "menu_suppliers",
    "nis2.dashboard": "menu_nis2",
    "nis2.list_notifications": "menu_nis2_notifications",
    "nis2.list_supply_chain": "menu_nis2_supply_chain",
    "nis2.list_continuity": "menu_nis2_continuity",
    "nis2.list_compliance": "menu_nis2_compliance",
    "gdpr.gdpr_dashboard": "menu_gdpr",
    "gdpr.list_processing": "menu_gdpr_processing",
    "gdpr.list_dpia": "menu_gdpr_dpia",
    "gdpr.list_dsar": "menu_gdpr_dsar",
    "gdpr.list_consent": "menu_gdpr_consent",
    "gdpr.list_controllers": "menu_gdpr_controllers",
    "gdpr.list_notices": "menu_gdpr_notices",
    "reports.index": "menu_reports",
}

SECTION_MENU_PERMISSION = {
    "ISMS Framework": "menu_clauses",
    "Risk & Assets": "menu_risks",
    "Operations": "menu_incidents",
    "NIS2 Compliance": "menu_nis2",
    "GDPR Compliance": "menu_gdpr",
    "Reporting": "menu_reports",
}

MENU_READ_WRITE = {
    "menu_controls": "menu_controls_write",
    "menu_soa": "menu_soa_write",
    "menu_reviews": "menu_reviews_write",
    "menu_kpi": "menu_kpi_write",
    "menu_risks": "menu_risks_write",
    "menu_assets": "menu_assets_write",
    "menu_assignments": "menu_assignments_write",
    "menu_incidents": "menu_incidents_write",
    "menu_policies": "menu_policies_write",
    "menu_filled_forms": "menu_filled_forms_write",
    "menu_audits": "menu_audits_write",
    "menu_business_continuity": "menu_business_continuity_write",
    "menu_capa": "menu_capa_write",
    "menu_training": "menu_training_write",
    "menu_suppliers": "menu_suppliers_write",
    "menu_nis2": "menu_nis2_write",
    "menu_nis2_notifications": "menu_nis2_notifications_write",
    "menu_nis2_supply_chain": "menu_nis2_supply_chain_write",
    "menu_nis2_continuity": "menu_nis2_continuity_write",
    "menu_nis2_compliance": "menu_nis2_compliance_write",
    "menu_gdpr": "menu_gdpr_write",
    "menu_gdpr_processing": "menu_gdpr_processing_write",
    "menu_gdpr_dpia": "menu_gdpr_dpia_write",
    "menu_gdpr_dsar": "menu_gdpr_dsar_write",
    "menu_gdpr_consent": "menu_gdpr_consent_write",
    "menu_gdpr_controllers": "menu_gdpr_controllers_write",
    "menu_gdpr_notices": "menu_gdpr_notices_write",
}

PERMISSION_GROUPS = {
    "Dashboard": ["menu_dashboard"],
    "ISMS Framework": ["menu_clauses", "menu_clauses_write", "menu_controls", "menu_controls_write", "menu_soa", "menu_soa_write", "menu_reviews", "menu_reviews_write", "menu_kpi"],
    "Risk & Assets": ["menu_risks", "menu_risks_write", "menu_assets", "menu_assets_write", "menu_assignments", "menu_assignments_write"],
    "Operations": ["menu_incidents", "menu_incidents_write", "menu_policies", "menu_policies_write", "menu_filled_forms", "menu_filled_forms_write", "menu_audits", "menu_audits_write", "menu_business_continuity", "menu_business_continuity_write", "menu_capa", "menu_capa_write", "menu_training", "menu_training_write", "menu_suppliers", "menu_suppliers_write"],
    "NIS2 Compliance": ["menu_nis2", "menu_nis2_write", "menu_nis2_notifications", "menu_nis2_notifications_write", "menu_nis2_supply_chain", "menu_nis2_supply_chain_write", "menu_nis2_continuity", "menu_nis2_continuity_write", "menu_nis2_compliance", "menu_nis2_compliance_write"],
    "GDPR Compliance": ["menu_gdpr", "menu_gdpr_write", "menu_gdpr_processing", "menu_gdpr_processing_write", "menu_gdpr_dpia", "menu_gdpr_dpia_write", "menu_gdpr_dsar", "menu_gdpr_dsar_write", "menu_gdpr_consent", "menu_gdpr_consent_write", "menu_gdpr_controllers", "menu_gdpr_controllers_write", "menu_gdpr_notices", "menu_gdpr_notices_write"],
    "Reporting": ["menu_reports"],
    "Administration": ["user_view", "user_create", "user_edit", "user_delete", "role_view", "role_create", "role_edit", "role_delete", "audit_log_view", "system_config"],
    "Data": ["control_view", "control_create", "control_edit", "control_delete", "risk_view", "risk_create", "risk_edit", "risk_delete", "asset_view", "asset_create", "asset_edit", "asset_delete", "incident_view", "incident_create", "incident_edit", "incident_delete", "policy_view", "policy_create", "policy_edit", "policy_delete", "audit_view", "audit_create", "audit_edit", "audit_delete", "supplier_view", "supplier_create", "supplier_edit", "supplier_delete", "soa_view", "soa_edit", "report_view", "report_export", "nis2_edit", "management_review_view", "management_review_create", "management_review_edit", "management_review_delete", "business_continuity_view", "business_continuity_create", "business_continuity_edit", "business_continuity_delete", "capa_view", "capa_create", "capa_edit", "capa_delete", "training_view", "training_edit", "training_delete"],
}
